name: Checks

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      clipboard: ${{ steps.filter.outputs.clipboard }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            clipboard:
              - 'packages/clipboard/**'

  lint:
    uses: ./.github/workflows/_lint.yml

  lint-rust:
    needs: detect-changes
    if: needs.detect-changes.outputs.clipboard == 'true'
    uses: ./.github/workflows/_lint-rust.yml

  test:
    uses: ./.github/workflows/_test.yml

  build-native:
    needs: detect-changes
    if: needs.detect-changes.outputs.clipboard == 'true'
    uses: ./.github/workflows/_build-native.yml

  test-native:
    needs: build-native
    uses: ./.github/workflows/_test-native.yml
